// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-jayVwd56x2sNNN2aYOPoK7-z4Z-FqE',
    appId: '1:215518049988:web:0f2c223fd3e0a1a6b9bb91',
    messagingSenderId: '215518049988',
    projectId: 'my-mood-tracking-app',
    authDomain: 'my-mood-tracking-app.firebaseapp.com',
    storageBucket: 'my-mood-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdisVSAbluyFJ4pURCojyHrwzCnwq7B90',
    appId: '1:215518049988:android:b558bb25fac2e1fab9bb91',
    messagingSenderId: '215518049988',
    projectId: 'my-mood-tracking-app',
    storageBucket: 'my-mood-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKmf2Vi6FudCRyd8Bwa3-IM4EcHAjrdP8',
    appId: '1:215518049988:ios:dbd58c9a8775d7acb9bb91',
    messagingSenderId: '215518049988',
    projectId: 'my-mood-tracking-app',
    storageBucket: 'my-mood-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.moodtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKmf2Vi6FudCRyd8Bwa3-IM4EcHAjrdP8',
    appId: '1:215518049988:ios:dbd58c9a8775d7acb9bb91',
    messagingSenderId: '215518049988',
    projectId: 'my-mood-tracking-app',
    storageBucket: 'my-mood-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.moodtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4-jayVwd56x2sNNN2aYOPoK7-z4Z-FqE',
    appId: '1:215518049988:web:3b4eec95df871935b9bb91',
    messagingSenderId: '215518049988',
    projectId: 'my-mood-tracking-app',
    authDomain: 'my-mood-tracking-app.firebaseapp.com',
    storageBucket: 'my-mood-tracking-app.firebasestorage.app',
  );
}
